services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Olawale@11
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data